/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * 打开文件或文件夹（使用系统默认程序）
 *
 * - 如果是文件，使用系统默认程序打开
 * - 如果是文件夹，在文件管理器中打开
 *
 * @param path - 要打开的文件或文件夹的绝对路径
 * @throws 如果路径不存在会抛出错误
 * @example
 * ```js
 * import { open } from 'open-native'
 * // 打开文件
 * open('C:\\Users\\test\\document.pdf')
 * // 打开文件夹
 * open('C:\\Users\\test\\Downloads')
 * ```
 */
export declare function open(path: string): void

/**
 * 使用指定程序打开文件
 *
 * @param path - 要打开的文件的绝对路径
 * @param app - 用于打开文件的应用程序名称或路径
 *   - Windows: 可以是程序名（如 `notepad`）或完整路径
 *   - macOS: 应用程序名称（如 `TextEdit`）或 bundle identifier
 *   - Linux: 可执行文件名称（如 `gedit`）
 * @throws 如果路径不存在会抛出错误
 * @example
 * ```js
 * import { openWith } from 'open-native'
 * // 使用记事本打开文本文件
 * openWith('C:\\Users\\test\
ote.txt', 'notepad')
 * // 使用 VS Code 打开
 * openWith('/path/to/file.js', 'code')
 * ```
 */
export declare function openWith(path: string, app: string): void

/**
 * 在文件管理器中打开文件夹并选中指定文件
 *
 * - 在 Windows 上使用 explorer /select
 * - 在 macOS 上使用 open -R
 * - 在 Linux 上尝试使用 dbus 或 xdg-open
 *
 * @param path - 要在文件管理器中显示的文件或文件夹的绝对路径
 * @throws 如果路径不存在会抛出错误
 * @example
 * ```js
 * import { reveal } from 'open-native'
 * // 在文件管理器中显示文件
 * reveal('C:\\Users\\test\\document.pdf')
 * ```
 */
export declare function reveal(path: string): void
